services:
  db:
    image: postgres:17
    container_name: carava-carwash-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - carwash-network

  owner-app:
    build: ./owner-service
    env_file:
      - .env
    container_name: carava-owner-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    restart: always
    networks:
      - carwash-network

  customer-app:
    build: ./customer-service
    env_file:
      - .env
    container_name: carava-customer-app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    restart: always
    networks:
      - carwash-network

volumes:
  postgres-data:

networks:
  carwash-network:
    driver: bridge