spring:
  application:
    name: carava-carwash-owner

  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    data:
      web:
        pageable:
          default-page-size: 20
          max-page-size: 100

  data:
    redis:
      host: redis
      port: 6379
      password:
      timeout: 2000ms

server:
  port: 8080

jwt:
  secret: "carwash-jwt-secret-key-for-authentication-and-authorization-process-must-be-256-bits-long"
  access-token-expire-time: 3600000
  refresh-token-expire-time: 604800000

logging:
  level:
    com.carava.carwash: DEBUG
    org.springframework.security: DEBUG